configuration: Release

before_build:
  - nuget restore
after_build:
  - nuget pack ExampleClient/ExampleClient.csproj -properties Configuration=Release -outputdirectory ./ExampleClient

artifacts:
  - path: 'ExampleClient\**\*.nupkg'
    name: NuGet package
  - path: 'ExampleClient\bin\Release\**\*.dll'
    name: Dynamic link library
