configuration: Release

before_build:
  - nuget restore
after_build:
  - nuget pack ConsoleExample/ConsoleExample.csproj -properties Configuration=Release -outputdirectory ./ConsoleExample

artifacts:
  - path: 'ConsoleExample\**\*.nupkg'
    name: NuGet package
  - path: 'ConsoleExample\bin\Release\**\*.dll'
    name: Dynamic link library
