configuration: Release

before_build:
  - nuget restore
after_build:
  - nuget pack ExampleClient/ExampleClient.csproj -properties Configuration=Release -outputdirectory ./ExampleClient

artifacts:
  - path: 'ExampleClient\**\*.nupkg'
    name: NuGet package
  - path: 'ExampleClient\bin\Release\**\*.dll'
    name: Dynamic link library

nuget:
  account_feed: true
  project_feed: true

deploy:
  - provider: NuGet
    api_key:
      secure: h3NF5jE2LHIE5Cuotq1A3rPi7hFwVCCa6LdLbK0Ttxg=
    skip_symbols: true
    server: https://ci.appveyor.com/nuget/holyshared-5jt22p7viwxw
    artifact: /ExampleClient.*\.nupkg/
  - provider: GitHub
    description: ''
    auth_token:
      secure: 5BACOnTzglTUgXtoo59lfh+OSNROGoubJ41tU6m4DwoWcsXqVHsY+ixLWKSQAbEA
    artifact: /ExampleClient.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 49QkzF75Ru6N4dnfcMO6K9aJYsWumjh+wUx+8Nwo2O5rP95+bDgR3J0/OYpan4oPJeMI89oe8ynwWIaMWbU6hkDBfVMPSEBM6n5EUPRClYs=
